import { ThemeConfig } from 'antd';

export const themes: ThemeConfig = {
    components: {
        Button: {
            fontFamily: 'Inter, system-ui, Avenir, Helvetica, Arial, sans-serif',
            fontSizeLG: 26,
            fontWeight: 400,
            defaultBorderColor: '#e46f50',
            defaultActiveBorderColor: '#E46F50',
            defaultHoverBorderColor: '#F1B287',
            defaultBg: 'transparent',
            defaultActiveBg: 'transparent',
            defaultHoverBg: 'transparent',
            defaultColor: '#e46f50',
            colorText: '#e46f50',
            defaultActiveColor: '#F1B287',
            defaultHoverColor: '#F1B287',
            controlHeightLG: 52,
            colorPrimaryBg: '#e46f50',
            primaryColor: '#fff',
            colorPrimary: '#E46F50',
            colorPrimaryHover: '#F1B287',
            colorPrimaryActive: '#F1B287',
            colorBgContainerDisabled: '#E46F50',
            colorTextDisabled: '#ffffff75',
        },
        Input: {
            controlHeightLG: 52,
            controlOutline: '#333',
            borderRadiusLG: 0,
            colorBorder: '#333',
            hoverBorderColor: '#333',
            lineWidthFocus: 0,
            activeBorderColor: '#333',
            controlOutlineWidth: 1,
            colorBorderBg: 'none',
            boxShadow: 'none',
            boxShadowSecondary: 'none',
        },
        Select: {
            borderRadius: 0,
            controlHeight: 52,
            colorBorder: '#e46f50',
            optionSelectedColor: '#fff',
            optionSelectedFontWeight: 400,
            optionSelectedBg: '#e46f50',
            borderRadiusLG: 0,
        },
    },
};
